coverage >=0

diff --git a/.github/actions/coverage/action.yml b/.github/actions/coverage/action.yml
--- a/.github/actions/coverage/action.yml
+++ b/.github/actions/coverage/action.yml
@@ -7,7 +7,7 @@ runs:
     - name: Install dependencies
       shell: bash
       run: |
-        sudo apt-get install -y cmake bc gcovr
+        sudo apt-get install -y bc gcovr
     
     - name: "Run coverage"
       shell: bash
@@ -19,8 +19,8 @@ runs:
         COVERAGE_LOG=$PROJECT_PATH/coverage_output.txt
 
         ctest --test-dir build/test --output-on-failure -VV \
-          1> "$TEST_LOG" \
-          2> "$TEST_ERRORS"
+          1> $TEST_LOG \
+          2> $TEST_ERRORS
       
         if [ -s $TEST_ERRORS ]; then
           echo "Errors during tests:"
@@ -32,21 +32,20 @@ runs:
 
         COVERAGE_RESULT=$(grep "TOTAL" $COVERAGE_LOG | awk '{print $NF}' | cut -d '%' -f 1)
 
-      #  if [ "$(echo "$COVERAGE_RESULT > 1" | bc)" -eq 1 ]; then
-      #    echo "Ok"
-      #    exit 0
-      #  else
-      #    echo "Coverage failed:"
-      #    cat $COVERAGE_LOG
-      #    exit 1
-      #  fi
+        if [ "$(echo "$COVERAGE_RESULT >=0 " | bc)" -eq 1 ]; then
+          echo "Ok"
+          exit 0
+        else
+          echo "Coverage failed:"
+          cat $COVERAGE_LOG
+          exit 1
+        fi
 
-    - uses: actions/upload-artifact@v4
-      if: failure()
-      with:
-        path: |
-          ./test_output.txt
-          ./test_errors.txt
-          ./coverage_output.txt
-        retention-days: 3
-
+        - uses: actions/upload-artifact@v4
+          if: failure()
+          with:
+            path: |
+              ./test_output.txt
+              ./test_errors.txt
+              ./coverage_output.txt
+            retention-days: 3
